import { HiOutlineChevronLeft, HiOutlineChevronRight } from "react-icons/hi";
import { IoMdArrowDropdown } from "react-icons/io";
import alert from "../../../../images/dashboard/admin/alert.svg";
import Image from "next/image";
import coder from "../../../../images/dashboard/admin/Coder.svg";

import close from "../../../../images/dashboard/admin/Stroke.svg";
import doneIcon from "../../../../images/dashboard/admin/Close Square.svg";

const Dashboard = () => {
  return (
    <section className="pt-[24px] bg-[#F2F2F2] pb-[57px]">
      <div className="container mx-auto xl:px-20 px-5">
        <div className="bg-[#ffca7b66] p-5 rounded-[10px]">
          <div className="flex gap-[10px] mb-[17px]">
            <Image src={alert} alt="alert image" />
            <h4 className="text-[#404040] text-base">
              Disclaimer : Teachers should modify as needed.
            </h4>
          </div>
          <p className="text-[#404040cc] text-xs">
            MyIEP Buddy is intended to serve as a supportive tool and source of
            inspiration for special education teachers creating individualized
            education plans. While we strive to provide accurate and useful
            information, our platform should not be considered a substitute for
            professional judgment or expertise. Users are responsible for
            tailoring and modifying the content generated by MyIEP Buddy to meet
            the specific needs and requirements of their students. Always
            consult with relevant educational professionals and adhere to your
            school or district&apos;s policies and guidelines when creating
            IEPs.
          </p>
        </div>
        <div className="p-[30px] bg-[#212936] rounded-[20px] mt-5">
          <div className="flex justify-between">
            <div>
              <h4 className="text-white text-2xl mb-3">Welcome back, Ardian</h4>
              <p className="text-base text-[#D1D1D1]">
                Satisfy your curiosity with thousands of creative classes.
                Discover new skills, deepen existing
              </p>
              <button className="mt-[30px] py-[10px] px-[30px] text-[12px] leading-[18px] text-[#555555] bg-[#A9F8FD] rounded-[10px] ">
                Get Started
              </button>
            </div>
            <div>
              <Image src={coder} alt="coder image" />
            </div>
          </div>
        </div>
        <div className="mt-5">
          <h4 className="text-[#616161] text-2xl mb-[10px]">My Students</h4>
        </div>
        <div className=" rounded-2xl overflow-hidden">
          <div className="flex justify-between items-center py-[14px] px-[31px] bg-white">
            <p className="text-[#5D7183] text-sm ">Student Name</p>
            <p className="text-[#5D7183] text-sm ">Summary</p>
            <div className="flex gap-2 sm:gap-4 ml-3">
              <Image src={close} alt="close icon" />
              <Image src={doneIcon} alt="done icon" />
            </div>
          </div>
          <div className="flex items-center justify-between py-[14px] px-[31px] gap-5 bg-[#F8F8F8]">
            <h6 className="text-[#0060AF] text-base">Example 1</h6>
            <p className="text-[#4d4d4dcc] text-base">
              At vero eos et accusamus et iusto odio dignissimos ducimus
              accusamus et iusto...
            </p>
          </div>
          <div className="flex items-center justify-between py-[14px] px-[31px] gap-5 bg-[#FFFFFF]">
            <h6 className="text-[#0060AF] text-base">Example 2</h6>
            <p className="text-[#4d4d4dcc] text-base">
              At vero eos et accusamus et iusto odio dignissimos ducimus
              accusamus et iusto...
            </p>
          </div>
          <div className="flex items-center justify-between py-[14px] px-[31px] gap-5 bg-[#F8F8F8]">
            <h6 className="text-[#0060AF] text-base">Example 3</h6>
            <p className="text-[#4d4d4dcc] text-base">
              At vero eos et accusamus et iusto odio dignissimos ducimus
              accusamus et iusto...
            </p>
          </div>
        </div>
        <div className=" px-5 pt-[111px] grid grid-cols-1 md:grid-cols-3 gap-2 items-center ">
          <div className="hidden md:block"></div>
          <div className="flex items-center gap-2 justify-center">
            <button className="bg-[#919EAB] opacity-50 rounded p-[10px] text-[#C4CDD5]">
              <HiOutlineChevronLeft className="" />
            </button>
            <span className="border border-[#0060AF] px-[15px] py-[7px] rounded bg-white text-[#0060AF]">
              1
            </span>
            <button className="text-[#C4CDD5] rounded p-[10px] border border-[#DFE3E8]">
              <HiOutlineChevronRight />
            </button>
          </div>
          <div className="flex gap-5 w-full justify-center md:justify-end">
            <p className="text-[#111827] text-sm ">Rows per page:</p>
            <p className="text-[#111827] text-sm flex">
              03
              <span>
                <IoMdArrowDropdown />
              </span>
            </p>
          </div>
        </div>
        <div className="flex gap-[10px] justify-end mt-[60px]">
          <button className="border bg-white rounded-[10px] border-[#A9F8FD] px-[46px] py-[10px] text-sm text-[#555555]">
            Copy
          </button>
          <button className="border bg-[#A9F8FD] rounded-[10px] border-[#A9F8FD] px-[46px] py-[10px] text-sm text-[#555555]">
            Save
          </button>
        </div>
      </div>
    </section>
  );
};

export default Dashboard;
